version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www
        depends_on:
            - mysql
        environment:
            DATABASE_URL: ${DATABASE_URL}

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_DATABASE}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql

    mercure:
        image: dunglas/mercure
        restart: unless-stopped
        ports:
            - "3000:80"
        environment:
            MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_SECRET}
            MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_JWT_SECRET}
            MERCURE_JWT_ALGORITHM: HS256
            MERCURE_EXTRA_DIRECTIVES: |
                cors_origins http://localhost
            MERCURE_CORS_ALLOWED_ORIGINS: "^http://localhost(:[0-9]+)?$$"
            MERCURE_PUBLISH_ALLOWED_ORIGINS: "^http://localhost(:[0-9]+)?$$"
            MERCURE_SUBSCRIBE_ALLOWED_ORIGINS: "^http://localhost(:[0-9]+)?$$"

            SERVER_NAME: ':80'

volumes:
    mysql_data:
